name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.UPAK_DEPLOY_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 51.250.110.59 >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          rsync -avz --exclude 'venv' --exclude '.git' --exclude '.github' . upak@51.250.110.59:/home/upak/upak-backend

      - name: Restart backend service
        run: |
          ssh upak@51.250.110.59 'source ~/.profile && cd ~/upak-backend && sudo systemctl restart upak-backend'
